version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      FLASK_APP: app.py  # Zmień na nazwę Twojego głównego pliku aplikacji
      FLASK_ENV: development      # Możesz zmienić na 'production'
      FLASK_DEBUG: 1